- .storybook/main.js
- src/hooks/mediaquery/useDevice.js
- src/utils/time-helper.js
-  time-helper를 추가하였습니다.
-  storybook main 문서를 수정하였습니다.
- 반응형 웹디자인을 위한 useDevice를 추가하였습니다
- 
- useDevice의 웹 미디어 쿼리 경계선은 디바이스별 해상도 분기점을 참고하였습니다.
> 🌈feat : 초기세팅 수정하기 및 util 기능들 추가

- package-lock.json
- package.json
- src/__mock__/datas/detailPage.mock.js
- src/assets/button/next_arrow.svg
- src/assets/button/prev_arrow.svg
- src/components/pages/ProductDetailPage.jsx
- src/components/ui/atoms/Button/UpdateButton.jsx
- src/components/ui/atoms/Button/UpdateButton.stories.jsx
- src/components/ui/atoms/Linebar/LineBar.jsx
- src/components/ui/atoms/Linebar/LineBar.stories.jsx
- src/components/ui/atoms/Tooltip/MTooltip.jsx
- src/components/ui/molecules/DeUserCard/DeUserCard.stories.jsx
- src/components/ui/molecules/DeUserProductButton/DeUserProductButton.jsx
- src/components/ui/molecules/ProductCard/ProductCard.jsx
- src/components/ui/molecules/SProductCarousel/Carousel.css
- src/components/ui/molecules/SProductCarousel/SProductCarousel.jsx
- src/components/ui/molecules/SProductCarousel/SProductCarousel.stories.jsx
- src/components/ui/organisms/DeImgSection/DeImgSection.jsx
- src/components/ui/organisms/DeImgSection/DeImgSection.stories.jsx
- src/components/ui/organisms/DeProductCategoryTag/DeProductCategoryTag.jsx
- src/components/ui/organisms/DeProductChartSection/DeProductChartSection.jsx
- src/components/ui/organisms/DeProductSection/DeProductSection.jsx
- src/components/ui/organisms/DeProductSection/DeProductSection.stories.jsx
- src/components/ui/organisms/DeRelatedCarousel/DeRelatedCarousel.jsx
- src/components/ui/organisms/DeRelatedCarousel/DeRelatedCarousel.stories.jsx
- src/components/ui/organisms/DeUserProductSection/DeUserProductSection.jsx
- src/components/ui/organisms/DeUserProductSection/DeUserProductSection.stories.jsx
- src/hooks/pageQuery/useLoadPage.js
- molecules/Map 이 나오기 이전까지 작업을 완료하였습니다.
-  모바일 페이지를 구현하기 위해서 작업을 진행합니다.
- Linebar 버그를 수정하였습니다.
- Tooltip 같은 경우 Mui 라이브러리를 사용할때도 생기는 경고 메세지가 있습니다. 문제없이 작동은 되나 추후 수정이 될수도있으니 보류사항입니다.
> 🌈feat : 디테일 페이지 중간완성 모바일 진행예정

- src/components/templates/ProductFormTemplate/ProductForm.jsx
- src/components/ui/organisms/DeFormImagePreviewGroup/DeFormImagePreviewGroup.jsx
- src/components/ui/organisms/DeFormTagGroup/DeFormTagGroup.jsx
- 물품 등록 페이지 오류 수정
- 태그, 이미지 리스트가 폼에 포함 안되던 오류 수정
>  📝fix : 물품 등록 페이지 버그 수정

- src/App.js
- styled-component ThemeProvider에 미디어쿼리(useDevice)값 추가
- 공통 styled component의 ThemeProvider에 반응형 관련 테마를 추가
- AS-IS: useDevice로 받아온 값을 props로 넘겨서 사용
```
// 1. useDevice에서 꺼내옴
const { isDesktop } = useDevice()
```
```
// 2. prop에 추가
<S.PreviewGroup isDesktop={isDesktop}>...</S.PreviewGroup>
```
```
// 3. styled-component 부분
S.PreviewGroup = styled.div`
flex-direction: ${({ isDesktop }) => isDesktop ? 'row' : 'column'};
`
```
- TO-BE: styled-component를 사용하는 다른 부분에서는 기존 테마 사용하던것과 똑같은 방법으로 사용
```
S.PreviewGroup = styled.div`
flex-direction: ${({ theme }) => theme.isDesktop ? 'row' : 'column'};
`
```
>  🌈feat : ThemeProvider에 미디어쿼리 useDevice  추가

- src/components/templates/ProductFormTemplate/ProductForm.jsx
- src/components/ui/atoms/Input/style.js
- src/components/ui/organisms/DeFormImagePreviewGroup/DeFormImagePreviewGroup.jsx
- 물품 등록/수정 페이지 반응형 추가
- [공통] Input atom의 Input에 1023px 이하 디바이스에 width:100% 속성을 추가했습니다.
- 물품 등록/수정 페이지 반응형 추가
>  🌈feat : 물품 등록/수정 폼 반응형  추가

- package-lock.json
- package.json
- src/components/templates/ProductFormTemplate/ProductForm.jsx
- src/components/ui/atoms/Button/Button.stories.jsx
- src/components/ui/atoms/Button/WishButton.stories.jsx
- src/components/ui/atoms/Input/Input.stories.jsx
- src/components/ui/atoms/Tag/Tag.stories.jsx
- src/components/ui/molecules/InputGroup/InputGroup.stories.jsx
- 물품 등록/수정 폼 공통 Container로 변경 및 스토리 정리
- 물품 등록/수정 폼 공용 Container로 변경
- story 코드 정리 (theme provider 지움)
>  🚧refactor : 공통 Container로 변경 및 스토리 정리

- src/__mock__/apis/myPage.api.js
- src/__mock__/datas/myPage.mock.js
- src/__mock__/handler.jsx
- src/apis/service/user.api.js
- src/components/pages/MyPage.jsx
- src/components/templates/MyPageTemplate/MyContent.jsx
- src/components/templates/MyPageTemplate/MyProfileTemplate.jsx
- src/components/ui/organisms/MyHeader/MyHeader.jsx
- src/hooks/pageQuery/useLoadUser.js
- 마이페이지 헤더 목데이터 연결
- 마이페이지 헤더 프로필 영역 수정
- 마이페이지 헤더 목데이터 data 추가
- 마이페이지 헤더 목데이터 msw api 추가
- 프로필 클릭 시 연결되는 이미지 변경 템플릿 추가
- 마이페이지에서 오류가 난다면 새로고침 한번 해주세요.. 나중에 ErrorBoundary 적용하겠슴다
>  🌈feat : 마이페이지 헤더 목데이터 연결

- src/App.js
- src/__mock__/datas/listPage.mock.js
- src/components/pages/MainPage.jsx
- src/components/pages/ProductDetailPage.jsx
- src/components/pages/ProductListPage.jsx
- src/components/pages/ProductSearchPage.jsx
- src/components/pages/ProductUserListPage.jsx
- src/components/templates/ErrorPageTemplate/ErrorPage.stories.jsx
- src/components/templates/ErrorPageTemplate/ErrorPageTemplate.jsx
- src/components/templates/MainPageTemplate/MainPageTemplateSkeleton.jsx
- src/components/templates/ProductListTemplate/ProductListSkeletonTemplate.jsx
- src/components/ui/organisms/DeProductSection/DeProductSection.jsx
- src/components/ui/organisms/ProductList/ProductListSkeleton.jsx
- src/hooks/pageQuery/useLoadPage.js
- src/routes/router.jsx
- 로딩 상태를 자연스럽게 보여주기 위한 suspense를 추가하였습니다.
- dev이외에 main 브랜치에 이슈 템플릿을 추가하여 템플릿 작성이 가능합니다.
- 모든 페이지에서 스켈레톤 페이지 또는 로딩 페이지가 있으면 서스펜스를 통해 자연스러운 페이지 이동이 가능할 것 같습니다.
- suspense를 추가하였기에 라우터의 코드가 변경이 되었습니다.
> 🌈feat : suspense, Skeleton page 추가

- src/routes/router.jsx
- 마이페이지 suspense 추가
- 마이페이지 헤더 렌더링 시 데이터가 불러오기 전 ui를 그리고 있어 마이페이지에 suspense 를 감싸줬습니다.
>  📝fix : 마이페이지 헤더 suspense 추가

- src/apis/service/user.api.js
- src/atom/header/atom.js
- src/components/modal/Side/SideBar.jsx
- src/components/pages/AuthPage.jsx
- src/components/pages/LandingPage.jsx
- src/components/templates/AuthPageTemplate/LoginTemplate.jsx
- src/components/templates/AuthPageTemplate/SignUpTemplate.jsx
- src/components/templates/AuthPageTemplate/validation.js
- src/components/ui/organisms/MainHeader/UserInfo.jsx
- src/hooks/service/user.service.js
- src/repositories/UserRepository.js
- src/routes/router.jsx
- 로그인 추가
- 로그아웃 추가
- 회원가입 추가
- 로그인 했을때 해당 사용자의 정보가 localstorage에 저장을 하였습니다. 헤더에 보여지게 수정해주세요
- 로그인 페이지와 회원가입 페이지에 추가 사항을 적었습니다. 수정해주세요
- 로그인 상태를 나타내는 전역변수 창에 수정사항을 적었습니다. 수정해주세요
-
-
> 🌈feat : 로그인, 로그아웃, 회원가입 기능 추가

- src/components/ui/organisms/MainHeader/MainHeader.jsx
- 💄style : 코드 포맷팅 누락
- 코드 포맷팅 수정
-
-
> 💄style : 코드 포맷팅 누락

- src/apis/service/user.api.js
signUp 코드 포맷팅이 누락이라 다시한번 pr을 보냅니다
> 💄style : 코드 포맷팅누락

- src/apis/service/product.api.js
- src/components/pages/ProductUpdatePage.jsx
- src/components/templates/ProductFormTemplate/ProductForm.jsx
- src/components/ui/molecules/Map/ProductFormMap.jsx
- src/components/ui/organisms/DeFormImagePreviewGroup/DeFormImagePreviewGroup.jsx
- src/components/ui/organisms/DeFormTagGroup/DeFormTagGroup.jsx
- 물품 등록, 수정 api 실제 데이터 연결
- 물품 등록 기능 연결
- 물품 수정 기능 연결
- msw 기준 변수명 실제 변수명으로 변경
- 파일 드래그로 이미지 업로드 기능 추가
- 기존 이미지는 드래그 앤 드롭으로 순서 변경 불가 (다시 등록해야 순서 변경 가능)
- 내가 쓴 글이 아닌 다른 사람의 글 수정하려고 하면 '해당 물품을 수정할 수 있는 권한이 없습니다.' alert 후 메인페이지 이동 로직 추가
>  🌈feat : 물품 등록, 수정 api 연결

- src/components/ui/atoms/Button/WishButton.jsx
-찜버튼에 아이콘 효과 추가
- 찜버튼 클릭 시 아이콘 효과를 추가했습니다.
>  🌈feat : 찜버튼 mui 아이콘 효과 추가

- src/components/ui/organisms/MainFooter/MainFooter.jsx
- 푸터 스타일 변경
- 이미지가 아닌 svg로 변경 & 색상 변경
- git 아이콘에 github 링크 연결
- 파도가 낮아졌습니다 ... 😝
전
후
>  🌈feat : 푸터 스타일 변경

- src/components/templates/ProductFormTemplate/ProductForm.jsx
- src/components/templates/ProductFormTemplate/style.js
- src/components/ui/organisms/DeFormImagePreviewGroup/DeFormImagePreviewGroup.jsx
- src/utils/formatter.js
- 물품 등록 페이지 반응형 css추가
- 반응형 css 추가
- 제한 금액 최대 일억원까지 가능하도록 조건 추가
- 금액 한글로 표시 기능 추가
>  🌈feat : 물품 등록 페이지 반응형 css 추가

- src/apis/service/review.api.js
- src/components/modal/Review/Review.jsx
- src/components/modal/Review/ReviewDetail.jsx
- src/components/modal/Review/validator.js
- src/components/templates/MyPageTemplate/MyContent.jsx
- src/components/templates/MyPageTemplate/MyReviewTemplate.jsx
- src/components/templates/ProductDetailTemplate/ProductDetailTemplate.jsx
- src/components/ui/molecules/ReviewCard/ReviewCard.jsx
- src/components/ui/molecules/ReviewCard/ReviewCard.stories.jsx
- src/components/ui/organisms/ReviewProducts/ReviewIsNullCard.jsx
- src/components/ui/organisms/ReviewProducts/ReviewIsNullProducts.jsx
- src/components/ui/organisms/ReviewProducts/ReviewProducts.jsx
- src/consts/product.js
- src/hooks/service/review.service.js
-  🌈feat : 리뷰작성 기능 추가
- 리뷰작성, 수정, 삭제기능이 추가 되었습니다.
- 기존의 물품 등록, 수정 페이지를 재사용하여 만들었습니다. 마이페이지에서 이동하므로 페이지가 따로 없이 모달로 만들었습니다.
- 기존의 수정페이지에서 수정할 시 페이지가 멈추던 오류가 그대로 남아있습니다.
- 리뷰를 작성하거나 수정할경우 온도가 음수까지 떨어지는 경우가 있습니다. 해당 사항은 백엔드 오류로서 현재 파악중에 있습니다.
> 🌈feat : 리뷰작성 기능 추가

- src/apis/service/review.api.js
- src/components/modal/Review/Review.jsx
- src/components/modal/Review/ReviewDetail.jsx
- src/components/modal/Review/validator.js
- src/components/templates/MyPageTemplate/MyContent.jsx
- src/components/templates/MyPageTemplate/MyReviewTemplate.jsx
- src/components/templates/ProductDetailTemplate/ProductDetailTemplate.jsx
- src/components/ui/molecules/Map/ProductMap.jsx
- src/components/ui/molecules/ProductCard/ProductCard.jsx
- src/components/ui/molecules/ReviewCard/ReviewCard.jsx
- src/components/ui/molecules/ReviewCard/ReviewCard.stories.jsx
- src/components/ui/organisms/DeImgSection/DeImgSection.jsx
- src/components/ui/organisms/DeProductCategoryTag/DeProductCategoryTag.jsx
- src/components/ui/organisms/DeProductSection/DeProductSection.jsx
- src/components/ui/organisms/MaSection/MaSection.jsx
- src/components/ui/organisms/ProductList/ProductList.jsx
- src/components/ui/organisms/ProductList/ProductList.stories.jsx
- src/components/ui/organisms/ReviewProducts/ReviewIsNullCard.jsx
- src/components/ui/organisms/ReviewProducts/ReviewIsNullProducts.jsx
- src/components/ui/organisms/ReviewProducts/ReviewProducts.jsx
- src/consts/product.js
- src/hooks/service/review.service.js
- 🔨Refactor : issue의 요청사항대로 변경
- 모바일 사이즈일시 카드가 2개씩 보이도록 수정
- 디테일 페이지 왼쪽 이미지 배너의 크기 최대 크기 500으로 수정
- 아래 이미지들도 맞추어 수정
- 디테일 페이지 이동시 다른 이미지를 클릭했을때 원본이미지가 다시 로드되는 버그 수정
- 리뷰 작성 목록에도 2개씩 보이도록 수정하였습니다.
-
> 🔨Refactor: issue 요청사항 변경

- src/components/ui/organisms/MainHeader/HeaderChatAlarm.jsx
- src/components/ui/organisms/MainHeader/MainHeader.jsx
>  📝fix : 소켓 에러로 인한 헤더 채팅알림 주석

- src/components/templates/ProductListTemplate/ProductListTemplate.jsx
- src/components/ui/organisms/MaLineBanner/MaLineBanner.jsx
-  🌈feat : 검색시 해당 키워드 보여주기 추가
- 검색시 해당 키워드 보여주기 추가
- 검색시 해당 키워드 보여주기 추가
-
> 🌈feat : 검색시 해당 키워드 보여주기 추가

- src/atom/header/atom.js
- src/components/templates/AuthPageTemplate/LoginTemplate.jsx
- src/hooks/service/user.service.js
- src/repositories/LoginCookie.js
- src/routes/private.jsx
-  🌈feat : 쿠키를 통한 로그인 유효성검사 추가
-  기존에 새로고침하면 초기화 되던 로그인 상태에서 쿠키로 값을 바꾸었습니다,
- 쿠키는 하루동안 유지가 되게 설정하였습니다.
- 원래 해당 로그인 상태의 쿠키는 백엔드에서 관리해주는것으로 알고있습니다!
- 세션에 있는 로컬 스토리지값을 임의로 지울시 에러가 발생합니다..? (굳이 이렇게 까지 해야하나 싶긴한데 발생하였습니다)
-
> 🌈feat : 쿠키를 통한 로그인 유효성검사 추가

- src/components/templates/ProductDetailTemplate/ProductDetailTemplate.jsx
- 🌈feat : 상세 페이지 채팅방 갯수 추가
- 🌈feat : 상세 페이지 채팅방 갯수 추가
- 추가된 데이터 중에서 상세페이지의 채팅방 갯수를 추가하였습니다.
-
> 🌈feat : 상세 페이지 채팅방 갯수 추가

- src/components/templates/ProductDetailTemplate/ProductDetailTemplate.jsx
- src/components/ui/molecules/DeProductTitle/DeProductTitle.jsx
- src/components/ui/molecules/DeUserCard/DeUserCard.jsx
- src/components/ui/molecules/ProductCard/ProductCard.jsx
- src/components/ui/molecules/ReviewCard/ReviewCard.jsx
- src/components/ui/organisms/DeUserProductSection/DeUserProductSection.jsx
- src/components/ui/organisms/MaSection/MaSection.jsx
- src/components/ui/organisms/ProductList/ProductList.jsx
- src/components/ui/organisms/ReviewProducts/ReviewIsNullCard.jsx
- 받아올 수 없는 데이터를 임시 데이터로 수정하였습니다.
- 
- 백엔드의 수정이 늦어서 임시로 데이터를 추가하였습니다.
> 🌈feat : 임시 데이터 추가

- src/components/templates/LandingPageTemplate/LandingPageTemplate.jsx
- src/components/templates/LandingPageTemplate/style.js
- 랜딩페이지 css 수정
- 헤더에 연결된 랜딩페이지에서는 사람이 푸터에 잠겨있어서 ㅠㅠ 수정했습니다..
- 이미지 최대 넓이를 지정하여 이미지가 너무 커지지 않게 수정
-
-
>  💄style : 랜딩페이지 css 수정

- src/hooks/pageQuery/@config.js
> 📚docs : cacheTime 수정

- src/components/templates/AuthPageTemplate/LoginTemplate.jsx
- src/components/templates/AuthPageTemplate/validation.js
- src/components/ui/organisms/MyMenu/MyMenu.jsx
- src/hooks/pageQuery/@config.js
> 📝fix : 회원가입 버그 수정
